/**
 * Contruct a map of fields that will be used by gauntlet
 * @param hdlBranch - String of name of hdl branch to use for bootfile source
 * @param linuxBranch - String of name of linux branch to use for bootfile source
 * @param bootPartitionBranch - String of name of boot partition branch to use for bootfile source, set to 'NA' if hdl and linux is to be used
 * @param firmwareVersion - String of name of firmware version branch to use for pluto and m2k
 * @param bootfile_source - String location of bootfiles. Options: sftp, artifactory, http, local
 * @return map of initially populated field/value pairs
 */
private def call(hdlBranch, linuxBranch, bootPartitionBranch,firmwareVersion, bootfile_source) {
    return [
            hdlBranch: hdlBranch,
            linuxBranch: linuxBranch,
            bootPartitionBranch: bootPartitionBranch,
            branches: ( bootPartitionBranch == 'NA')? hdlBranch : bootPartitionBranch,
            filetype: ( bootPartitionBranch == 'NA')? ' --filetype="hdl_linux"' : ' --filetype="boot_partition"',
            url_template: 'NA',
            firmwareVersion: firmwareVersion,
            bootfile_source: bootfile_source,
            job_trigger: 'manual',
            agents_online: '',
            debug: false,
            board_map: [:],
            stages: [],
            agents: [],
            boards: [],
            required_hardware: [],
            required_agent: [],
            include_variants: false,
            firmware_boards: ['pluto','m2k'],
            enable_docker: false,
            docker_image: 'tfcollins/test-harness-ci-ubuntu-22_04:latest',
            docker_args: ['MATLAB','Vivado'],
            docker_host_mode: true,
            update_nebula_config: true,
            check_device_status: true,
            nebula_config_source: 'netbox',
            netbox_test_agent: false,
            netbox_ip: '',
            netbox_port: '',
            netbox_base_url: '',
            netbox_token: '',
            netbox_devices_status: null,
            netbox_devices_role: null,
            netbox_devices_tag: null,
            netbox_nebula_template: null,
            netbox_include_variants: true,
            netbox_include_children: true,
            netbox_allow_disable: true,
            enable_update_boot_pre_docker: false,
            board_sub_categories : ['rx2tx2'],
            setup_called: false,
            nebula_debug: false,
            nebula_local_fs_source_root: '/var/lib/tftpboot',
            elastic_server: '',
            iio_uri_source: 'ip',
            iio_uri_baudrate: 921600,
            configure_called: false,
            required_libraries: ['nebula', 'libiio', 'telemetry'],
            pytest_libiio_repo: 'https://github.com/tfcollins/pytest-libiio.git',
            pytest_libiio_branch: 'master',
            pyadi_iio_repo: 'https://github.com/analogdevicesinc/pyadi-iio.git',
            pyadi_iio_branch: 'main',
            libad9361_iio_repo: 'https://github.com/analogdevicesinc/libad9361-iio.git',
            libad9361_iio_branch : 'main',
            nebula_repo: 'https://github.com/sdgtt/nebula.git',
            nebula_branch: 'master',
            libiio_repo: 'https://github.com/analogdevicesinc/libiio.git',
            libiio_branch: 'v0.25',
            telemetry_repo: 'https://github.com/sdgtt/telemetry.git',
            telemetry_branch: 'master',
            matlab_release: 'R2021a',
            matlab_repo: 'https://github.com/analogdevicesinc/TransceiverToolbox.git',
            matlab_branch: 'master',
            matlab_commands: [],
            matlab_timeout: '10m',
            matlab_license: 'machine',
            no_os_repo: 'https://github.com/analogdevicesinc/no-OS.git',
            no_os_branch: 'master',
            vivado_ver: '2021.2',
            nebula_config_repo: 'https://github.com/sdgtt/nebula-config.git',
            nebula_config_branch: 'master',
            kuiper_checker_repo: 'https://github.com/sdgtt/kuiper-post-build-checker.git',
            kuiper_checker_branch: 'master',
            send_results: false,
            test_adi_diagnostics: false, // set to true to run diagnostics on the net before running the gauntlet
            elastic_logs : [:],
            max_retry: 3,
            recovery_ref: "SD",
            log_artifacts: false,
            credentials_id: '',
            toolbox_generated_bootbin: false,
            ml_toolbox: '',
            ml_branch: '',
            ml_build: '',
            ml_test_stages: 0,
            internal_stages_to_skip: [:], // Number of stages to skip. Used for test skipping for MATLAB
            update_lib_requirements: false, // Set to true to run installation of requirements.txt of nebula and telemetry
            update_container_lib: false, // Set to true to force update libiio, nebula, telemetry base on master branch inside docker container
            nebula_config_path: ''
    ]
}
